language: python
python:
    - 2.6
    - 2.7
    - 3.4
install:
    - pip install -r condiment/config/data/python-dependencies.list
    - pip install coveralls
script:
    - coverage run --source . --timid --branch setup.py test
after_success:
    - coveralls
